name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore
      run: dotnet restore StringTheory.slnx
    - name: Build
      run: dotnet build StringTheory.slnx --configuration Release --no-restore
    - name: Publish
      run: dotnet publish StringTheory/StringTheory.csproj --configuration Release --no-build
